#!/usr/bin/env bash

########################################
# Constants
########################################

readonly PROJECTS_DIR="$HOME/Projects"

########################################
# Variables
########################################

PROJECT_NAME=""
PROJECT_PATH=""

########################################
# Helper Functions
########################################

usage() {
    cat <<EOF
Usage:
    dev <project>

Example:
    dev minishell
    dev webserv
EOF
}

error() {
    echo "Error: $*" >&2
}

########################################
# Functions
########################################

find_project() {
}

parse_arguments() {

}

########################################
# Main
########################################

main() {

}

main "$@"
