# Prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Mouse
set -g mouse on

# True color
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"

# Window numbers
set -g base-index 1

# Pane numbers
setw -g pane-base-index 1

# Split shortcuts
bind | split-window -h
bind - split-window -v

# Reload config
bind r source-file ~/.tmux.conf \; display "Config reloaded"

# Better navigation
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Status bar
set -g status-position top

set -g status-style bg=black,fg=white

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'catppuccin/tmux'

run '~/.tmux/plugins/tpm/tpm'
